### ISSUE TITLE
Running the framework on a Slurm instance 

### ISSUE THREAD

**Issue by MohamedLEGH** [sacs-epfl/decentralizepy#16]
Slurm (https://slurm.schedmd.com/) is an open source cluster management and job scheduling system. I want to run a simulation on a slurm cluster but I don't know how I can parallelize the tasks. Indeed the simulator necessitates that I give the IP address of the nodes but I don't know in advance on which nodes my code will run (maybe I can tweak this but it's a bit complex). 

Did anyone already tried to run the framework on a slurm instance, with multiples nodes ?

Thanks,
Mohamed Amine

**Comment by rishi-s8** [comment]
Hi Mohamed, sorry for the late reply. We never really tried running it on a Slurm instance, but we did try RunAI. Unfortunately, in the current state, the framework does not support autoscaling. Therefore, all nodes (and all machines) need to run together. If you can ensure that all nodes can be scheduled together on your Slurm instance, then it should work. A good addition to DecentralizePy would be auto scaling, i.e., trying to migrate nodes on the available instances, but we are a bit short staffed for adding this. Good luck!
