### ISSUE TITLE
synchronization barrier mechanism

### ISSUE THREAD

**Issue by MohamedLEGH** [sacs-epfl/decentralizepy#18]
If I understand correctly there is a synchronization barrier mechanism so all nodes start at the same time. But is there a synchronization mechanism to ensure that all nodes are on the same cycle (or iteration) ? Does a node wait for all other nodes before starting the next round ?

**Comment by dimiarbre** [comment]
This depends on your implementation of `Node`. To my knowledge, most of them do, but I haven't tried all of them. For instance, in DPSGDNode, this is handled here: https://github.com/sacs-epfl/decentralizepy/blob/a5d46be907bc745652d5482c34117be388324439/src/decentralizepy/node/DPSGDNode.py#L96
Hope this helps

**Comment by rishi-s8** [comment]
Thanks @dimiarbre for your response.

Indeed, the synchronization is built into the algorithms here. Nodes wait for messages from others before moving on. In the case of D-PSGD, neighboring nodes can be almost one round apart, but the aggregation only uses the messages of the locally-correct round.

**Comment by MohamedLEGH** [comment]
Ok thanks a lot, it's very clear.
